#!/bin/sh
# Load functions and variables
. /usr/bin/common
export NEWT_COLORS='root=,black border=white,black window=white,black title=white,black textbox=white,black listbox=white,black'

whiptail_height="$(($(tput lines) - 6))"
whiptail_width="$(($(tput cols) - 20))"

while true; do
  CHOICE="$(whiptail --nocancel --title "infinity" --menu '' $whiptail_height $whiptail_width 7 \
    '1' 'checkra1n' \
    '2' 'Project Sandcastle' \
    '3' 'SSH' \
    '4' 'Shell' \
    '5' 'Shut down' \
    '6' 'Reboot' 3>&1 1>&2 2>&3)"
  case "$CHOICE" in
    1)
      clear
      /usr/bin/checkra1n
      ;;
    2)
      /usr/bin/projectsandcastle_menu
      ;;
    3)
      clear
      /usr/bin/ssh_into_ios
      ;;
    4)
      clear
      break
      ;;
    5)
      infinity_logo
      sleep 2
      /usr/sbin/shutdown now
      ;;
    6)
      infinity_logo
      sleep 2
      /usr/sbin/reboot
      ;;
  esac
done
