#!/bin/bash
# This file is from https://github.com/Albert-S-Briscoe/projectsandcastlefix
# Based on https://github.com/306bobby/projectsandcastlefix and https://projectsandcastle.org/


# Check for an Android filesystem.

LABEL=
VOLUME=
VOLUMES=`ls -1 /dev/disk0s1s* | sort -V`

# Might as well leave this.
if [[ -z $VOLUMES ]]; then
	echo "Can't find any apfs volumes. Something is very wrong."
	exit 1
fi

# Search for android volume
for i in ${VOLUMES}; do
	LABEL=`/System/Library/Filesystems/apfs.fs/apfs.util -p $i`
	if [ "${LABEL}" == "Android" ]; then
		VOLUME=$i
		break
	fi
done
if [ ! -b ${VOLUME} ]; then
	echo "Cannot find Android volume. You probably haven't installed sandcastle."
	exit 0
fi


echo "Mounting ${VOLUME}"
mkdir -p /tmp/mnt
mount -t apfs ${VOLUME} /tmp/mnt 
if [ $? -ne 0 ]; then
	echo "Failed to mount volume. Are you running as root?";
	exit 1
fi

if [ ! -e /tmp/mnt/nand ]; then
	echo "No nand file found. Sandcastle already uninstalled."
	umount /tmp/mnt
	echo "Unmounted /tmp/mnt"
	exit 0
fi

# Check to make sure removing /tmp/mnt/usr won't break a ios install ...that happens to be in a volume named Android? I just want to be safe and not brick people's phones
if [ -e /tmp/mnt/Library ]; then
	echo "Either you did something incredibly strange with partitions or something is very wrong."
	umount /tmp/mnt
	echo "Unmounted /tmp/mnt"
	exit 1
fi




# At this point, we've hopefully confirmed that the correct volume is mounted and there's a sandcastle nand on it.


echo -n "This will free about 2gb. Are you sure you want to delete all Android files? (type yes to continue): "
read -r CONFIRM
if [ ! "$CONFIRM" == "yes" ]; then
	umount /tmp/mnt
	echo "Unmounted /tmp/mnt"
	exit 0
fi

echo "Removing nand file..."
rm -rf /tmp/mnt/nand

# Remove firmware files
rm -rf /tmp/mnt/usr
sync

umount /tmp/mnt
echo "Sandcastle removed. Unmounted /tmp/mnt"
