#!/bin/bash
# This file is from https://github.com/Albert-S-Briscoe/projectsandcastlefix
# Based on https://github.com/306bobby/projectsandcastlefix and https://projectsandcastle.org/


# Check for an Android filesystem, and create one if there isn't

LABEL=
VOLUME=
VOLUMES=`ls -1 /dev/disk0s1s* | sort -V`

# I can't find any way to delete accidentally created apfs volumes. This should help prevent making them in the first place.
if [[ -z $VOLUMES ]]; then
	echo "Can't find any apfs volumes. Something is very wrong."
	exit 1
fi

# Search for android volume
for i in ${VOLUMES}; do
	LABEL=`/System/Library/Filesystems/apfs.fs/apfs.util -p $i`
	if [ "${LABEL}" == "Android" ]; then
		VOLUME=$i
		break;
	fi
done
if [ ! -b ${VOLUME} ]; then
	echo "Creating new Android volume"
	newfs_apfs -A -v Android -e /dev/disk0s1
fi


# Double check that there's a valid filesystem

LABEL=
VOLUME=
VOLUMES=`ls /dev/disk0s1s* | sort -V`

for i in ${VOLUMES}; do
	LABEL=`/System/Library/Filesystems/apfs.fs/apfs.util -p $i`
	if [ "${LABEL}" == "Android" ]; then
		VOLUME=$i
		break;
	fi
done
if [ ! -b ${VOLUME} ]; then 
	echo "Android volume not found. This should have been caught earlier"
	exit 1
fi



echo "Mounting ${VOLUME}"
mkdir -p /tmp/mnt
mount -t apfs ${VOLUME} /tmp/mnt 
if [ $? -ne 0 ]; then
	echo "Failed to mount volume. Are you running as root?";
	exit 1
fi

if [ -e /tmp/mnt/nand ]; then
	echo "Nand image already downloaded."
else
	rm -rf /tmp/mnt/nand
	echo "Starting download of the nand file. This will take a few minutes"
	wget http://assets.checkra.in/downloads/sandcastle/88b1089d97fe72ab77af8253ab7c312f8e789d49209234239be2408c3ad89a34/nand.gz -O /tmp/mnt/nand.gz
	if [ $? -ne 0 ]; then
		echo "Failed to download nand. Are you connected to wifi?"
		umount /tmp/mnt
		echo "unmounted /tmp/mnt"
		exit 1
	fi
	echo "Decompressing nand image"
	gunzip -d /tmp/mnt/nand.gz
	if [ $? -ne 0 ]; then
		echo "Failed to decompress nand. Network interrupted? gzip not installed?"
		umount /tmp/mnt
		echo "unmounted /tmp/mnt"
		exit 1
	fi
	sync
fi

echo "Applying touchscreen/WiFi patch and copying driver files."

# The Hack.
echo -n "  " | dd bs=1 seek=1145078249 count=2 status=none conv=notrunc of=/tmp/mnt/nand

# The Fix.
mkdir -p /tmp/mnt/usr/share/firmware/
cp -rn /usr/share/firmware/* /tmp/mnt/usr/share/firmware/

umount /tmp/mnt
echo "Unmounted /tmp/mnt"
